"""Shared Run Record approval summary proof shape."""

from __future__ import annotations

APPROVAL_SUMMARY_ID_FIELD = "id"
APPROVAL_SUMMARY_PROVIDER_FIELD = "provider"
APPROVAL_SUMMARY_STATUS_FIELD = "status"
APPROVAL_SUMMARY_REASON_FIELD = "reason"
APPROVAL_SUMMARY_UPDATED_AT_FIELD = "updated_at"
APPROVAL_SUMMARY_FIELDS = (
    APPROVAL_SUMMARY_ID_FIELD,
    APPROVAL_SUMMARY_PROVIDER_FIELD,
    APPROVAL_SUMMARY_STATUS_FIELD,
    APPROVAL_SUMMARY_REASON_FIELD,
    APPROVAL_SUMMARY_UPDATED_AT_FIELD,
)
APPROVAL_SUMMARY_KEYS = frozenset(APPROVAL_SUMMARY_FIELDS)
APPROVAL_SUMMARY_TEXT_FIELDS = (
    APPROVAL_SUMMARY_ID_FIELD,
    APPROVAL_SUMMARY_PROVIDER_FIELD,
    APPROVAL_SUMMARY_STATUS_FIELD,
    APPROVAL_SUMMARY_REASON_FIELD,
)
APPROVAL_SUMMARY_READY_STATUSES = frozenset({"resolved", "resume_requested"})
