"""Shared proof shapes for retrieved remote runner survivor artifacts."""

from __future__ import annotations

from fusekit.runner.run_state import RUN_STATE_FIELDS

REMOTE_REQUIRED_SURVIVOR_FILES = (
    "audit.jsonl",
    "fusekit.vault.json",
    "job.json",
    "run_state.json",
    "checkpoints.json",
    "gates.json",
    "gate_events.jsonl",
    "provider_strategies.json",
    "llm_contract.json",
    "runner_readiness.json",
    "worker_replacement_drill.json",
    "setup_receipt.json",
    "verification_report.json",
    "rollback_plan.json",
    "workspace_detonation.json",
    "run_record.json",
)
REMOTE_PRE_DETONATION_REQUIRED_SURVIVOR_FILES = tuple(
    filename
    for filename in REMOTE_REQUIRED_SURVIVOR_FILES
    if filename != "workspace_detonation.json"
)
REMOTE_OPTIONAL_SURVIVOR_FILES = ("setup_receipt.md", "visual.json")
REMOTE_PRE_DETONATION_FETCH_FILES = (
    *REMOTE_PRE_DETONATION_REQUIRED_SURVIVOR_FILES,
    *REMOTE_OPTIONAL_SURVIVOR_FILES,
)
REMOTE_PRE_DETONATION_FETCH_FILE_SET = frozenset(REMOTE_PRE_DETONATION_FETCH_FILES)
REMOTE_ALLOWED_SURVIVOR_FILES = (
    *REMOTE_REQUIRED_SURVIVOR_FILES,
    *REMOTE_OPTIONAL_SURVIVOR_FILES,
)
REMOTE_ALLOWED_SURVIVOR_FILE_SET = frozenset(REMOTE_ALLOWED_SURVIVOR_FILES)

REMOTE_JOB_APP_PATH_FIELD = "app_path"
REMOTE_JOB_ARTIFACTS_FIELD = "artifacts"
REMOTE_JOB_CHECKPOINTS_FIELD = "checkpoints"
REMOTE_JOB_CREATED_AT_FIELD = "created_at"
REMOTE_JOB_ID_FIELD = "id"
REMOTE_JOB_RUNNER_FIELD = "runner"
REMOTE_JOB_STATUS_FIELD = "status"
REMOTE_JOB_STEPS_FIELD = "steps"
REMOTE_JOB_UPDATED_AT_FIELD = "updated_at"
REMOTE_JOB_STATE_FIELDS = (
    REMOTE_JOB_APP_PATH_FIELD,
    REMOTE_JOB_ARTIFACTS_FIELD,
    REMOTE_JOB_CHECKPOINTS_FIELD,
    REMOTE_JOB_CREATED_AT_FIELD,
    REMOTE_JOB_ID_FIELD,
    REMOTE_JOB_RUNNER_FIELD,
    REMOTE_JOB_STATUS_FIELD,
    REMOTE_JOB_STEPS_FIELD,
    REMOTE_JOB_UPDATED_AT_FIELD,
)
REMOTE_JOB_STATE_KEYS = frozenset(REMOTE_JOB_STATE_FIELDS)

REMOTE_JOB_STEP_DETAIL_FIELD = "detail"
REMOTE_JOB_STEP_ID_FIELD = "id"
REMOTE_JOB_STEP_LABEL_FIELD = "label"
REMOTE_JOB_STEP_STATUS_FIELD = "status"
REMOTE_JOB_STEP_UPDATED_AT_FIELD = "updated_at"
REMOTE_JOB_STEP_FIELDS = (
    REMOTE_JOB_STEP_DETAIL_FIELD,
    REMOTE_JOB_STEP_ID_FIELD,
    REMOTE_JOB_STEP_LABEL_FIELD,
    REMOTE_JOB_STEP_STATUS_FIELD,
    REMOTE_JOB_STEP_UPDATED_AT_FIELD,
)
REMOTE_JOB_STEP_KEYS = frozenset(REMOTE_JOB_STEP_FIELDS)
REMOTE_JOB_STEP_REQUIRED_FIELDS = (
    REMOTE_JOB_STEP_ID_FIELD,
    REMOTE_JOB_STEP_LABEL_FIELD,
    REMOTE_JOB_STEP_STATUS_FIELD,
)

REMOTE_JOB_CHECKPOINT_DETAIL_FIELD = "detail"
REMOTE_JOB_CHECKPOINT_ID_FIELD = "id"
REMOTE_JOB_CHECKPOINT_LABEL_FIELD = "label"
REMOTE_JOB_CHECKPOINT_MASCOT_STATE_FIELD = "mascot_state"
REMOTE_JOB_CHECKPOINT_NEXT_ACTION_FIELD = "next_action"
REMOTE_JOB_CHECKPOINT_RESUME_HINT_FIELD = "resume_hint"
REMOTE_JOB_CHECKPOINT_STATUS_FIELD = "status"
REMOTE_JOB_CHECKPOINT_UPDATED_AT_FIELD = "updated_at"
REMOTE_JOB_CHECKPOINT_FIELDS = (
    REMOTE_JOB_CHECKPOINT_DETAIL_FIELD,
    REMOTE_JOB_CHECKPOINT_ID_FIELD,
    REMOTE_JOB_CHECKPOINT_LABEL_FIELD,
    REMOTE_JOB_CHECKPOINT_MASCOT_STATE_FIELD,
    REMOTE_JOB_CHECKPOINT_NEXT_ACTION_FIELD,
    REMOTE_JOB_CHECKPOINT_RESUME_HINT_FIELD,
    REMOTE_JOB_CHECKPOINT_STATUS_FIELD,
    REMOTE_JOB_CHECKPOINT_UPDATED_AT_FIELD,
)
REMOTE_JOB_CHECKPOINT_KEYS = frozenset(REMOTE_JOB_CHECKPOINT_FIELDS)
REMOTE_JOB_CHECKPOINT_REQUIRED_FIELDS = (
    REMOTE_JOB_CHECKPOINT_ID_FIELD,
    REMOTE_JOB_CHECKPOINT_LABEL_FIELD,
    REMOTE_JOB_CHECKPOINT_STATUS_FIELD,
)

REMOTE_CHECKPOINTS_CHECKPOINTS_FIELD = "checkpoints"
REMOTE_CHECKPOINTS_JOB_ID_FIELD = "job_id"
REMOTE_CHECKPOINTS_STATUS_FIELD = "status"
REMOTE_CHECKPOINTS_UPDATED_AT_FIELD = "updated_at"
REMOTE_CHECKPOINTS_FIELDS = (
    REMOTE_CHECKPOINTS_CHECKPOINTS_FIELD,
    REMOTE_CHECKPOINTS_JOB_ID_FIELD,
    REMOTE_CHECKPOINTS_STATUS_FIELD,
    REMOTE_CHECKPOINTS_UPDATED_AT_FIELD,
)
REMOTE_CHECKPOINTS_KEYS = frozenset(REMOTE_CHECKPOINTS_FIELDS)

REMOTE_RUN_STATE_MISSING_FOR_DETONATION_FIELD = "missing_for_detonation"
REMOTE_RUN_STATE_NOTES_FIELD = "notes"
REMOTE_RUN_STATE_READY_TO_DETONATE_FIELD = "ready_to_detonate"
REMOTE_RUN_STATE_UPDATED_AT_FIELD = "updated_at"
REMOTE_RUN_STATE_EXTRA_FIELDS = (
    REMOTE_RUN_STATE_MISSING_FOR_DETONATION_FIELD,
    REMOTE_RUN_STATE_NOTES_FIELD,
    REMOTE_RUN_STATE_READY_TO_DETONATE_FIELD,
    REMOTE_RUN_STATE_UPDATED_AT_FIELD,
)
REMOTE_RUN_STATE_KEYS = frozenset((*RUN_STATE_FIELDS, *REMOTE_RUN_STATE_EXTRA_FIELDS))

REMOTE_PUBLIC_SURVIVOR_JSON_LABELS = {
    "job_state": "job",
    "run_state": "run_state",
    "checkpoints": "checkpoints",
    "worker_replacement_drill": "worker_replacement_drill",
}
