"""Shared setup receipt proof shape for launch gates."""

from __future__ import annotations

SETUP_RECEIPT_ACTIONS_FIELD = "actions"
SETUP_RECEIPT_RAW_SECRET_COUNT_FIELD = "raw_secrets_exposed"
SETUP_RECEIPT_TEXT_FIELDS = (
    "app_name",
    "vault_path",
    "live_url",
)
SETUP_RECEIPT_FIELDS = (
    SETUP_RECEIPT_ACTIONS_FIELD,
    *SETUP_RECEIPT_TEXT_FIELDS,
    SETUP_RECEIPT_RAW_SECRET_COUNT_FIELD,
)
SETUP_RECEIPT_ACTION_NAME_FIELD = "action"
SETUP_RECEIPT_ACTION_STATUS_FIELD = "status"
SETUP_RECEIPT_ACTION_DETAILS_FIELD = "details"
SETUP_RECEIPT_ACTION_REQUIRED_TEXT_FIELDS = (
    SETUP_RECEIPT_ACTION_NAME_FIELD,
    SETUP_RECEIPT_ACTION_STATUS_FIELD,
)
SETUP_RECEIPT_ACTION_FIELDS = (
    *SETUP_RECEIPT_ACTION_REQUIRED_TEXT_FIELDS,
    SETUP_RECEIPT_ACTION_DETAILS_FIELD,
)
SETUP_RECEIPT_KEYS = frozenset(SETUP_RECEIPT_FIELDS)
SETUP_RECEIPT_ACTION_KEYS = frozenset(SETUP_RECEIPT_ACTION_FIELDS)
