"""Shared Run Record timeline proof shape for launch gates."""

from __future__ import annotations

TIMELINE_REQUIRED_TEXT_FIELDS = (
    "id",
    "label",
    "status",
)
TIMELINE_STEP_OPTIONAL_TEXT_FIELDS = ("detail",)
TIMELINE_CHECKPOINT_OPTIONAL_TEXT_FIELDS = (
    "detail",
    "next_action",
    "resume_hint",
    "mascot_state",
)
TIMELINE_OPTIONAL_TEXT_FIELDS = TIMELINE_CHECKPOINT_OPTIONAL_TEXT_FIELDS
TIMELINE_TEXT_FIELDS = TIMELINE_REQUIRED_TEXT_FIELDS + TIMELINE_OPTIONAL_TEXT_FIELDS
TIMELINE_TIMESTAMP_FIELD = "updated_at"
TIMELINE_STEP_FIELDS = (
    *TIMELINE_REQUIRED_TEXT_FIELDS,
    *TIMELINE_STEP_OPTIONAL_TEXT_FIELDS,
    TIMELINE_TIMESTAMP_FIELD,
)
TIMELINE_CHECKPOINT_FIELDS = (
    *TIMELINE_REQUIRED_TEXT_FIELDS,
    *TIMELINE_CHECKPOINT_OPTIONAL_TEXT_FIELDS,
    TIMELINE_TIMESTAMP_FIELD,
)
TIMELINE_STEP_KEYS = frozenset(TIMELINE_STEP_FIELDS)
TIMELINE_CHECKPOINT_KEYS = frozenset(TIMELINE_CHECKPOINT_FIELDS)
TIMELINE_ENTRY_KEYS = TIMELINE_CHECKPOINT_KEYS
